/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 barstool.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/barstool.gltf?alt=media&token=888b7d52-c9af-4a11-b3dd-6750d97be090"
  );
  return (
    <group position={[2, -3, 0]} scale={0.1} dispose={null}>
      <mesh
        geometry={nodes.barstool.geometry}
        material={materials["barstool_mat.001"]}
        position={[0, 27.465, 0]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/barstool.gltf?alt=media&token=888b7d52-c9af-4a11-b3dd-6750d97be090"
);
