/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Briefcase.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Briefcase(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Briefcase.glb?alt=media&token=b729edbf-216e-47b1-991b-af6e5926f2c1"
  );
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.043}>
        <mesh geometry={nodes.Mesh.geometry} material={materials.Udim_1} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.Udim_2} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials.Udim_5} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials.Udim_3} />
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.Udim_4} />
      </group>
    </group>
  )
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Briefcase.glb?alt=media&token=b729edbf-216e-47b1-991b-af6e5926f2c1"
);
