/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Cycle_Glb.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cycle(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Cycle.glb?alt=media&token=98612069-2b28-4efa-ae33-7ec85af1326f"
  );
  return (
    <group position={[1, -1, 0]} scale={0.8} dispose={null}>
      <mesh
        geometry={nodes.Plane060.geometry}
        material={materials.Cycle}
        position={[0, -0.577, 0]}
        scale={6.681}
      />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Cycle.glb?alt=media&token=98612069-2b28-4efa-ae33-7ec85af1326f"
);
