/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 jars-cup.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jarscup(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/jars-cup.glb?alt=media&token=2ccdfa47-7c30-488a-a250-0ae65947678f"
  );
  return (
    <group position={[0, -1.3, 0]} scale={1} dispose={null}>
      <group position={[2.104, 0.053, 1.023]}>
        <mesh
          geometry={nodes.Plane.geometry}
          material={nodes.Plane.material}
          position={[0.53, 0.738, 0]}
          rotation={[0, 0, 0.421]}
          scale={0.079}
        />
      </group>
      <group position={[-1.01, 0.109, 0.531]} scale={1.252}>
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["Material.002"]}
          position={[0.449, 0.892, 0]}
          rotation={[0, 0, 0.341]}
          scale={0.063}
        />
      </group>
      <group position={[-0.318, -0.016, -0.879]} scale={1.575}>
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["Material.005"]}
          position={[0.368, 1.637, 0]}
          scale={0.079}
        />
      </group>
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.006"]}
        scale={6.554}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[0, 6.207, 0]}
        scale={6.559}
      />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/jars-cup.glb?alt=media&token=2ccdfa47-7c30-488a-a250-0ae65947678f"
);
