/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 locker.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Locker(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/locker.glb?alt=media&token=13454e8c-0411-46ae-9d19-7b258211343d"
  );
  return (
    <group position={[0, -1.3, 0]} scale={1.7} dispose={null}>
      <mesh
        geometry={nodes.Locker1.geometry}
        material={materials.Locker1}
        position={[-0.897, -0.012, -0.213]}
      >
        <mesh
          geometry={nodes.Drawer_Bottom_Locker1.geometry}
          material={materials.Locker1}
          position={[0.007, -0.753, 0.566]}
        />
        <mesh
          geometry={nodes.Drawer_Middle_Locker1.geometry}
          material={materials.Locker1}
          position={[0.007, 0.017, 0.566]}
        />
        <mesh
          geometry={nodes.Drawer_Top_Locker1.geometry}
          material={materials.Locker1}
          position={[0.007, 0.784, 0.567]}
        />
      </mesh>
      <mesh
        geometry={nodes.Locker2.geometry}
        material={materials.Locker2}
        position={[0.846, 0.194, -0.029]}
      >
        <mesh
          geometry={nodes.Door_Locker2.geometry}
          material={materials.Locker2}
          position={[0.36, 0, 0.319]}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/locker.glb?alt=media&token=13454e8c-0411-46ae-9d19-7b258211343d"
);
