/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 monitor.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Monitor(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/monitor.glb?alt=media&token=95570ab1-8ef7-4d93-a2e9-b65322a60d1a"
  );
  return (
    <group {...props} dispose={null}>
      <group scale={[0.02, 0.135, 0.184]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/monitor.glb?alt=media&token=95570ab1-8ef7-4d93-a2e9-b65322a60d1a"
);
