/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 shaker-bookshelf.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function ShakerBookshelf(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/shaker-bookshelf.glb?alt=media&token=487d0054-545e-4c51-9389-1647ec1f8832"
  );
  return (
    <group position={[1, -2, 0]} scale={1} dispose={null}>
      <mesh
        geometry={nodes["Component#2004"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.025, 0]}
      />
      <mesh
        geometry={nodes["Component#2005"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.914, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        geometry={nodes["Component#1004"].geometry}
        material={materials["[Wood Veneer 01].002"]}
      />
      <mesh
        geometry={nodes["Component#1005"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.94, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        geometry={nodes["Component#3010"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 0.66]}
      />
      <mesh
        geometry={nodes["Component#3011"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 1.118]}
      />
      <mesh
        geometry={nodes["Component#3012"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 1.575]}
      />
      <mesh
        geometry={nodes["Component#3013"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 2.032]}
      />
      <mesh
        geometry={nodes["Component#3014"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 0.051]}
      />
      <mesh
        geometry={nodes["Component#4010"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.076, 0.635]}
      />
      <mesh
        geometry={nodes["Component#4011"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.076, 1.092]}
      />
      <mesh
        geometry={nodes["Component#4012"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.076, 1.549]}
      />
      <mesh
        geometry={nodes["Component#4013"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.076, 2.007]}
      />
      <mesh
        geometry={nodes["Component#4014"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.076, 0.025]}
      />
      <mesh
        geometry={nodes["Component#5004"].geometry}
        material={materials["[Mirror 02].002"]}
        position={[0.441, 0.076, 0.076]}
      />
      <mesh
        geometry={nodes["Component#5005"].geometry}
        material={materials["[Mirror 02].002"]}
        position={[0.441, 0.864, 0.076]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        geometry={nodes["Rod#1004"].geometry}
        material={materials["[Mirror 02].002"]}
        position={[0.459, 0.077, 0.076]}
      />
      <mesh
        geometry={nodes["Rod#1005"].geometry}
        material={materials["[Mirror 02].002"]}
        position={[0.459, 0.863, 0.076]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={-1}
      />
      <mesh
        geometry={nodes["Component#6004"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.078, 0.076]}
      />
      <mesh
        geometry={nodes["Component#6005"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0.432, 0.47, 0.076]}
      />
      <mesh
        geometry={nodes["Component#7001"].geometry}
        material={materials["[Wood Veneer 01].002"]}
        position={[0, 0.025, 0.076]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[0.59, 0.145, 0.001]}
        scale={[11.652, 7.969, 1]}
      />
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/shaker-bookshelf.glb?alt=media&token=487d0054-545e-4c51-9389-1647ec1f8832"
);
