/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Shoe.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Shoe(props) {
  const { nodes, materials } = useGLTF('https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Shoe.glb?alt=media&token=c20c9dc5-08e8-4674-aee1-e3f2f8d3f9ac')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Shoe.geometry} material={materials.phong1SG} position={[0.002, 0.076, 0.005]} scale={0.149} />
    </group>
  )
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Shoe.glb?alt=media&token=c20c9dc5-08e8-4674-aee1-e3f2f8d3f9ac"
);
