/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 starirs.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Starirs(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/starirs.glb?alt=media&token=1f71b9e8-37f9-4345-b895-897c4f4f5c7e"
  );
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Metal_stair.geometry} material={materials['7001_metal']} />
      <mesh geometry={nodes.Wood_stair2.geometry} material={materials['7001_wood']} />
      <mesh geometry={nodes.Wood_stair3.geometry} material={materials['7001_wood']} />
      <mesh geometry={nodes.Wood_stair4.geometry} material={materials['7001_wood']} />
      <mesh geometry={nodes.Wood_stair5.geometry} material={materials['7001_wood']} />
      <mesh geometry={nodes.Wood_stair1.geometry} material={materials['7001_wood']} />
    </group>
  )
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/starirs.glb?alt=media&token=1f71b9e8-37f9-4345-b895-897c4f4f5c7e"
);
