/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 Suitcase.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Suitcase(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Suitcase.glb?alt=media&token=ecbfd721-7196-454d-9393-5d81c0d47785"
  );
  const { actions } = useAnimations(animations, group)

  // console.log(nodes)
  // console.log(materials)
  // This comment is to make my terminal detect changes as it does not deetect a file delete temporarily
  // To test again
  return (
    <group ref={group} position={[0, -1.3, 0]} scale={0.1} dispose={null}>
      <group name="Scene">
        <mesh
          name="Vintage_Suitcase"
          geometry={nodes.Vintage_Suitcase.geometry}
          material={materials.M_Case1}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh
            name="corners"
            geometry={nodes.corners.geometry}
            material={materials.M_Case1}
          />
          <mesh
            name="handle"
            geometry={nodes.handle.geometry}
            material={materials.M_Case1}
          />
          <mesh
            name="lining"
            geometry={nodes.lining.geometry}
            material={materials.M_Case1}
          />
          <mesh
            name="lock"
            geometry={nodes.lock.geometry}
            material={materials.M_Case1}
          />
          <mesh
            name="metal-edge"
            geometry={nodes["metal-edge"].geometry}
            material={materials.M_Case1}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/Suitcase.glb?alt=media&token=ecbfd721-7196-454d-9393-5d81c0d47785"
);
