/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 widemonitor.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Widemonitor(props) {
  const { nodes, materials } = useGLTF(
    "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/widemonitor.gltf?alt=media&token=2c491b33-64df-4258-8340-8887ef28e220"
  );
  return (
    <group {...props} dispose={null}>
      <group position={[1.64, -1.045, 0.12]} rotation={[0.004, -0.265, -0.003]} scale={[0.073, 0.049, 0.061]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials['Material.001']} />
      </group>
      <group position={[1.2, -1.037, 0.022]} rotation={[0, -0.215, 0]} scale={0.047}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder002_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder002_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.base} position={[0, -1.872, 0.412]} scale={[1, 0.932, 1]} />
      <group position={[0, -0.066, 0]} scale={[1, 1, 1.093]}>
        <mesh geometry={nodes.Cube_1.geometry} material={materials.mon} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.window} />
      </group>
      <mesh geometry={nodes.back_main.geometry} material={materials.base} position={[0, -0.066, -0.058]} scale={[0.564, 0.381, 0.057]} />
      <group position={[0.965, -1.037, -0.02]} rotation={[0, -0.146, 0]} scale={0.047}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder001_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.726, -1.035, -0.053]} rotation={[0, -0.128, 0]} scale={0.047}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder003_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder003_3.geometry} material={materials['Material.008']} />
      </group>
      <group position={[0.472, -1.04, -0.081]} rotation={[0, -0.087, 0]} scale={0.047}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cylinder004_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cylinder004_3.geometry} material={materials['Material.008']} />
      </group>
      <mesh geometry={nodes.lower_support.geometry} material={materials.base} position={[0, -1.119, -0.293]} />
      <mesh geometry={nodes.upper_support.geometry} material={materials.base} position={[0, -0.625, -0.293]} scale={[1.363, 0.877, 1.363]} />
      <mesh geometry={nodes.ONOFF.geometry} material={materials.button} position={[2.741, -1.066, 0.629]} rotation={[0, -0.459, 0]} scale={[0.055, 0.014, 0.015]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.button} position={[2.511, -1.055, 0.521]} rotation={[0, -0.379, 0]} scale={[0.032, 0.023, 0.014]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['button icon']} position={[2.384, -1.048, 0.506]} scale={[1.15, 0.761, 1.15]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials['button icon']} position={[2.26, -1.047, 0.452]} scale={1.139} />
      <mesh geometry={nodes.Text.geometry} material={materials['button icon']} position={[2.132, -1.047, 0.41]} rotation={[Math.PI / 2, 0, 0.348]} scale={0.019} />
      <mesh geometry={nodes.Text001.geometry} material={materials['button icon']} position={[2.51, -1.047, 0.561]} rotation={[Math.PI / 2, 0, 0.415]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['button icon']} position={[2.727, -1.047, 0.656]} rotation={[0, -0.455, 0]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['button icon']} position={[2.004, -1.046, 0.364]} rotation={[0, -0.309, 0.782]} scale={[0.089, 0.089, 0.029]} />
      <mesh geometry={nodes.Text002.geometry} material={materials.HDMI} position={[1.197, -0.998, -0.051]} rotation={[Math.PI / 2, 0, -2.957]} />
      <mesh geometry={nodes.Text003.geometry} material={materials.HDMI} position={[0.962, -0.997, -0.091]} rotation={[Math.PI / 2, 0, -2.989]} />
      <mesh geometry={nodes.Text004.geometry} material={materials.HDMI} position={[0.726, -1.001, -0.124]} rotation={[Math.PI / 2, 0, -3.035]} />
      <mesh geometry={nodes.Text005.geometry} material={materials.HDMI} position={[0.469, -0.998, -0.148]} rotation={[1.558, 0.001, -3.061]} />
    </group>
  )
}

useGLTF.preload(
  "https://firebasestorage.googleapis.com/v0/b/ranforte-a86c2.appspot.com/o/widemonitor.gltf?alt=media&token=2c491b33-64df-4258-8340-8887ef28e220"
);
